TelRehberMVC/Models/Kisiler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TelRehberMVC.Models
{
    [Table("Kisiler")]
    public class Kisiler
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(20),Required]
        public string Ad { get; set; }
        [StringLength(20),Required]
        public string Soyad { get; set; }
        [StringLength(20),Required]
        public string Telefon { get; set; }
        [StringLength(20)]
        public string Departman { get; set; }
        [StringLength(20)]
        public string yonetici { get; set; }

        


    }
}

TelRehberMVC/Models/Managers/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TelRehberMVC.Models.Managers
{
    public class DatabaseContext : DbContext
    {
        public DbSet<Kisiler> Kisiler { get; set; }
        
        
        

        public DatabaseContext()
        {
            Database.SetInitializer(new VeritabaniOlusturucu());
        }
    }
    public class VeritabaniOlusturucu : CreateDatabaseIfNotExists<DatabaseContext>
    {
        protected override void Seed(DatabaseContext context)
        {

            
            
           
            for (int i = 0; i < 20; i++)
            {
                
                Kisiler kisi = new Kisiler();
                kisi.Ad = FakeData.NameData.GetFirstName();
                kisi.Soyad = FakeData.NameData.GetSurname();
                kisi.Telefon = FakeData.PhoneNumberData.GetPhoneNumber();
                
                
                context.Kisiler.Add(kisi);
            }
            context.SaveChanges();

            






        } 
    }
}

TelRehberMVC/ViewModels/Home/HomePageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TelRehberMVC.Models;

namespace TelRehberMVC.ViewModels.Home
{
    public class HomePageViewModel
    {
        public List<Kisiler> Kisiler { get; set; }
    }
}

TelRehberMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TelRehberMVC.Models;
using TelRehberMVC.Models.Managers;
using TelRehberMVC.ViewModels.Home;

namespace TelRehberMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult homepage()
        {
            DatabaseContext db = new DatabaseContext();
            //List<Kisiler> kisiler = db.Kisiler.ToList();
            HomePageViewModel model = new HomePageViewModel();
            model.Kisiler = db.Kisiler.ToList();
            return View(model);
        }
    }
}

TelRehberMVC/Controllers/KisiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TelRehberMVC.Models;
using TelRehberMVC.Models.Managers;

namespace TelRehberMVC.Controllers
{
    public class KisiController : Controller
    {
        // GET: Kisi
        public ActionResult Yeni()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Yeni(Kisiler kisi)
        {
            DatabaseContext db = new DatabaseContext();
            db.Kisiler.Add(kisi);

            int sonuc = db.SaveChanges();
            if(sonuc > 0)
            {
                ViewBag.Result = "Kişi Kaydedilmiştir.";
                ViewBag.Status = "success";
            }
            else
            {
                ViewBag.Result = "Kişi Kaydedilememiştir.";
                ViewBag.Status = "denger";
            }

            
            return View();
        }
    }
}

TelRehberMVC/Views/Home/homepage.cshtml
@using TelRehberMVC.ViewModels.Home 
@model HomePageViewModel
@{
    ViewBag.Title = "homepage";
}

    <div class="container-fluid">
    
        <div class="row">
            <div class="col-md-12">
                <h2>Telefon Rehberi</h2>
                <hr />
            </div>
            
        </div>
        <div class="row ">
            <div class="col-md-4">

                <div>
                    @Html.ActionLink("Yeni Çalışan Ekle", "Yeni", "Kisi", null, new { @class = "btn btn-primary" })
                    <br /><br />
                </div>


                <ul class="list-group">
                    <li class="list-group-item active">
                        <h2>Çalışanlar</h2>

                    </li>
                </ul>



                <ul class="list-group">
                    @foreach (var kisiler in Model.Kisiler)
                    {

                        <li class="list-group-item ">
                            <span class="glyphicon glyphicon-user"></span> <b>@(kisiler.Ad)</b>
                        </li>


                    }

                </ul>
            </div>
            
            
            <div class="col-md-4">
                <br /><br /><br/>
                
                <ul class="list-group">
                    <li class="list-group-item active">
                        <h2>Telefonlar</h2>

                    </li>
                </ul>



                <ul class="list-group">
                    @foreach (var kisiler in Model.Kisiler)
                    {

                        <li class="list-group-item ">
                            @(kisiler.Telefon)(<i>@(kisiler.Ad)</i>)
                        </li>


                    }

                </ul>
            </div>







        </div>
    </div>

TelRehberMVC/Views/Kisi/Yeni.cshtml
@model TelRehberMVC.Models.Kisiler
@{
    ViewBag.Title = "Yeni";
}

<h2>Yeni Kisi</h2>

@using (Html.BeginForm())
{
    <div class="input-group">
        <span class="input-group-text" id="txtad"> Ad </span>
        @Html.TextBoxFor(x => x.Ad, new { @class="form-control", placeholder = "kişi adı",
        aria_describedby = "txtad"})
    </div>

    <br />

    <div class="input-group">
        <span class="input-group-text" id="txtsoyad"> Soyad </span>
        @Html.TextBoxFor(x => x.Soyad, new { @class="form-control", placeholder = "kişi soyadı",
        aria_describedby = "txtad"})
    </div>

    <br />

    <div class="input-group">
        <span class="input-group-text" id="txttelefon"> Telefon </span>
        @Html.TextBoxFor(x => x.Telefon, new { @class="form-control", placeholder = "kişi telefonu",
        aria_describedby = "txtad"})
    </div>

    <br />

    <div class="input-group">
        <input type="submit" value="Kaydet" class="btn btn-success" />
    </div>
    <br />

    <div class="input-group">
        @if (ViewBag.Result != null)
        {
                <div class="alert alert-@ViewBag.Status" role="alert" >
                    @ViewBag.Result
                </div>
          }
    </div>

}

TelRehberMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />


    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home Page", "homepage", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
</body>
</html>